# Generated by Django 2.2.10 on 2020-03-06 23:14

from django.db import migrations, models
import utils.abstract_models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('created', 'updated'),
            },
            bases=(models.Model, utils.abstract_models.ReprMixin),
        ),
    ]
